[package]
name = "k8s-cri"
version = "0.2.0"
license = "Apache-2.0"
authors = ["kflansburg <kevin.flansburg@gmail.com>"]
categories = ["api-bindings"]
description = "Bindings Kubernetes CRI"
edition = "2018"
keywords = ["client", "kubernetes", "k8s", "cri"]
repository = "https://github.com/kflansburg/k8s-cri"
documentation = "https://docs.rs/crate/k8s-cri"
readme = "README.md"

[dependencies]
tonic = { version = "0.2", features = ['tls'] }
prost = "0.6"

[build-dependencies]
prost-build = "0.6"

[build-dependencies.tonic-build]
version = "0.2"
default-features = false
features = ["prost", "transport"]

[dev-dependencies]
tokio = { version = "0.2", features = ['macros', 'net'] }
tower = "0.3"
