[package]
name = "k8s-cri"
version = "0.1.1"
license = "Apache-2.0"
authors = ["kflansburg <kevin.flansburg@gmail.com>"]
categories = ["api-bindings"]
description = "Bindings Kubernetes CRI"
edition = "2018"
keywords = ["client", "kubernetes", "k8s", "cri"]
repository = "https://github.com/kflansburg/k8s-cri"
documentation = "https://docs.rs/crate/k8s-cri"
readme = "README.md"

[dependencies]
tonic = "0.2"
prost = "0.6"

[build-dependencies.tonic-build]
version = "0.2"
default-features = false
features = ["prost"]
